name: Kernel Build

on:
workflow_dispatch:
push:
branches:
- bandido

jobs:
build:
runs-on: ubuntu-22.04

steps:
  - uses: actions/checkout@v4
    with:
      submodules: recursive

  - name: Install deps
    run: |
      sudo apt update
      sudo apt install -y bc bison build-essential flex git libssl-dev libelf-dev python3 clang lld llvm device-tree-compiler

  - name: Build
    run: |
      export ARCH=arm64
      mkdir out
      make O=out vendor/r8q_eur_open_defconfig
      make -j$(nproc) O=out ARCH=arm64 CC=clang LLVM=1 LLVM_IAS=1

  - name: Upload
    uses: actions/upload-artifact@v4
    with:
      name: kernel
      path: out/arch/arm64/boot/
